/* eslint-disable operator-linebreak */

// WEB3 CONTEXT
export const SET_WEB3_PROVIDER = 'SET_WEB3_PROVIDER'
export const SET_ADDRESS = 'SET_ADDRESS'
export const SET_ADDRESS_PROVIDER = 'SET_ADDRESS_PROVIDER'
export const SET_WEB3AUTH_ADDRESS = 'SET_WEB3AUTH_ADDRESS'
export const RESET_WEB3_PROVIDER = 'RESET_WEB3_PROVIDER'
export const SET_CHAIN_ID = 'SET_CHAIN_ID'
